# This workflow will install Python dependencies and run tests with tox
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox

name: Titan Client

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pwd
          ls -lh
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install requirements.txt
          python -m pip install test-requirements.txt
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
